# Generated by Django 2.1.5 on 2019-01-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='numberSod',
            new_name='numberSold',
        ),
    ]
