# Generated by Django 2.1.5 on 2019-02-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20190205_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='pid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
