# Generated by Django 2.1.5 on 2019-02-14 11:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello', '0010_auto_20190212_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='hello/static/hello/no_image.png', upload_to='hello/static/hello'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='developerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='developerid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchases',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
