# Generated by Django 2.1.5 on 2019-02-12 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_auto_20190212_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 12, 14, 53, 39, 500526)),
        ),
    ]
