# Generated by Django 2.1.5 on 2019-02-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_purchases_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
