# Generated by Django 2.1.5 on 2019-02-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_merge_20190212_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='static/hello/no_image.png', upload_to='static/hello'),
        ),
    ]
