# Generated by Django 2.1.5 on 2019-02-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_game_image'),
        ('hello', '0012_auto_20190212_1501'),
    ]

    operations = [
    ]
